[package]
name = "voting-system"
version = "1.0.0"
authors = ["tuvuanh27"]

[addresses]
my_addrx="_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
